// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/mydata.proto

package mydata

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Mydata service

func NewMydataEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Mydata service

type MydataService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (Mydata_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Mydata_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (Mydata_BidiStreamService, error)
}

type mydataService struct {
	c    client.Client
	name string
}

func NewMydataService(name string, c client.Client) MydataService {
	return &mydataService{
		c:    c,
		name: name,
	}
}

func (c *mydataService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "Mydata.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mydataService) ClientStream(ctx context.Context, opts ...client.CallOption) (Mydata_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "Mydata.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &mydataServiceClientStream{stream}, nil
}

type Mydata_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*ClientStreamRequest) error
}

type mydataServiceClientStream struct {
	stream client.Stream
}

func (x *mydataServiceClientStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *mydataServiceClientStream) Close() error {
	return x.stream.Close()
}

func (x *mydataServiceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *mydataServiceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *mydataServiceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *mydataServiceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *mydataService) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Mydata_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "Mydata.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &mydataServiceServerStream{stream}, nil
}

type Mydata_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type mydataServiceServerStream struct {
	stream client.Stream
}

func (x *mydataServiceServerStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *mydataServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *mydataServiceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *mydataServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *mydataServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *mydataServiceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mydataService) BidiStream(ctx context.Context, opts ...client.CallOption) (Mydata_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "Mydata.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &mydataServiceBidiStream{stream}, nil
}

type Mydata_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type mydataServiceBidiStream struct {
	stream client.Stream
}

func (x *mydataServiceBidiStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *mydataServiceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *mydataServiceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *mydataServiceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *mydataServiceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *mydataServiceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *mydataServiceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Mydata service

type MydataHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, Mydata_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, Mydata_ServerStreamStream) error
	BidiStream(context.Context, Mydata_BidiStreamStream) error
}

func RegisterMydataHandler(s server.Server, hdlr MydataHandler, opts ...server.HandlerOption) error {
	type mydata interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type Mydata struct {
		mydata
	}
	h := &mydataHandler{hdlr}
	return s.Handle(s.NewHandler(&Mydata{h}, opts...))
}

type mydataHandler struct {
	MydataHandler
}

func (h *mydataHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.MydataHandler.Call(ctx, in, out)
}

func (h *mydataHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.MydataHandler.ClientStream(ctx, &mydataClientStreamStream{stream})
}

type Mydata_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type mydataClientStreamStream struct {
	stream server.Stream
}

func (x *mydataClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *mydataClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *mydataClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *mydataClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *mydataClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *mydataHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.MydataHandler.ServerStream(ctx, m, &mydataServerStreamStream{stream})
}

type Mydata_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type mydataServerStreamStream struct {
	stream server.Stream
}

func (x *mydataServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *mydataServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *mydataServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *mydataServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *mydataServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *mydataHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.MydataHandler.BidiStream(ctx, &mydataBidiStreamStream{stream})
}

type Mydata_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type mydataBidiStreamStream struct {
	stream server.Stream
}

func (x *mydataBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *mydataBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *mydataBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *mydataBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *mydataBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *mydataBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
